services:
  - type: web
    name: face-spoof-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.10.13
